org.gradle.jvmargs=-Xmx4g -Xms4m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m

group=com.eygraber
version=0.1.1-SNAPSHOT

POM_URL=https://github.com/eygraber/metro-contribution-guard/
POM_SCM_URL=https://github.com/eygraber/metro-contribution-guard/
POM_SCM_CONNECTION=scm:git:git://github.com/eygraber/metro-contribution-guard.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/eygraber/metro-contribution-guard.git

POM_LICENCE_NAME=MIT
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=eygraber
POM_DEVELOPER_NAME=Eliezer Graber
POM_DEVELOPER_URL=https://github.com/eygraber

#Gradle
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true

#Misc
dependency.analysis.compatibility=NONE
dependency.analysis.print.build.health=true
